package com.archibus.app.reservation.domain;

/**
 * Room Configuration domain object.
 *
 * @author Yorik Gerlo
 * @since 21.3
 *        <p>
 *        Suppress PMD warning CyclomaticComplexity in this class.
 *        <p>
 *        Justification: equals method generated by Eclipse for comparing all primary key
 *        attributes.
 */
@SuppressWarnings("PMD.CyclomaticComplexity")
public class RoomConfiguration {

    /** Base prime number used for the hashCode method. */
    private static final int HASHCODE_PRIME = 31;

    /** The building code. */
    private String buildingId;

    /** The config id. */
    private String configId;

    /** The config id. */
    private String configName;

    /** The floor code. */
    private String floorId;

    /** The room code. */
    private String roomId;

    /** The excluded configurations for this configuration. */
    private String excludedConfigs;

    /**
     * Get the building id.
     *
     * @return the building id
     */
    public String getBuildingId() {
        return this.buildingId;
    }

    /**
     * Set the building id.
     *
     * @param buildingId the building id
     */
    public void setBuildingId(final String buildingId) {
        this.buildingId = buildingId;
    }

    /**
     * Get the room configuration id.
     *
     * @return the configuration id
     */
    public String getConfigId() {
        return this.configId;
    }

    /**
     * Set the configuration id.
     *
     * @param configId the room configuration id
     */
    public void setConfigId(final String configId) {
        this.configId = configId;
    }

    /**
     * Get the floor id.
     *
     * @return the floor id
     */
    public String getFloorId() {
        return this.floorId;
    }

    /**
     * Set the floor id.
     *
     * @param floorId the floor id
     */
    public void setFloorId(final String floorId) {
        this.floorId = floorId;
    }

    /**
     * Get the room id.
     *
     * @return the room id
     */
    public String getRoomId() {
        return this.roomId;
    }

    /**
     * Set the room id.
     *
     * @param roomId the room id
     */
    public void setRoomId(final String roomId) {
        this.roomId = roomId;
    }

    /**
     * Get the excluded configuration ids.
     *
     * @return the excluded configuration ids
     */
    public String getExcludedConfigs() {
        return this.excludedConfigs;
    }

    /**
     * Set the excluded configuration ids.
     *
     * @param excludedConfigs the excluded configuration ids
     */
    public void setExcludedConfigs(final String excludedConfigs) {
        this.excludedConfigs = excludedConfigs;
    }

    /**
     * Getter for the configName property.
     *
     * @return the configName property.
     */
    public String getConfigName() {
        return this.configName;
    }

    /**
     * Setter for the configName property.
     *
     * @param configName the configName to set.
     */
    public void setConfigName(final String configName) {
        this.configName = configName;
    }

    /**
     * Hash code method generated by Eclipse based on primary key fields. {@inheritDoc}
     * <p>
     * Suppress PMD warning NPathComplexity in this method.
     * <p>
     * Justification: hashCode is generated by Eclipse.
     */
    @SuppressWarnings("PMD.NPathComplexity")
    @Override
    public int hashCode() {
        final int prime = HASHCODE_PRIME;
        int result = 1;
        result = prime * result + ((this.buildingId == null) ? 0 : this.buildingId.hashCode());
        result = prime * result + ((this.configId == null) ? 0 : this.configId.hashCode());
        result = prime * result + ((this.floorId == null) ? 0 : this.floorId.hashCode());
        result = prime * result + ((this.roomId == null) ? 0 : this.roomId.hashCode());
        return result;
    }

    /**
     * Equals method generated by Eclipse based on primary key fields. {@inheritDoc}
     * <p>
     * Suppress PMD warnings NPathComplexity and OnlyOneReturn in this method.
     * <p>
     * Justification: Room Configuration equals method generated by Eclipse for all primary key
     * attributes.
     */
    // CHECKSTYLE:OFF Justification: equals method generated by Eclipse.
    @SuppressWarnings({ "PMD.NPathComplexity", "PMD.OnlyOneReturn" })
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final RoomConfiguration other = (RoomConfiguration) obj;
        if (this.buildingId == null) {
            if (other.buildingId != null) {
                return false;
            }
        } else if (!this.buildingId.equals(other.buildingId)) {
            return false;
        }
        if (this.configId == null) {
            if (other.configId != null) {
                return false;
            }
        } else if (!this.configId.equals(other.configId)) {
            return false;
        }
        if (this.floorId == null) {
            if (other.floorId != null) {
                return false;
            }
        } else if (!this.floorId.equals(other.floorId)) {
            return false;
        }
        if (this.roomId == null) {
            if (other.roomId != null) {
                return false;
            }
        } else if (!this.roomId.equals(other.roomId)) {
            return false;
        }
        return true;
    }
    // CHECKSTYLE:ON

    /**
     * Get the configuration pkeys for a given room arrangement.
     *
     * @param arrangement the arrangement to convert to a configuration
     * @return the configuration
     */
    public static RoomConfiguration getConfiguration(final RoomArrangement arrangement) {
        final RoomConfiguration configuration = new RoomConfiguration();
        configuration.setBuildingId(arrangement.getBlId());
        configuration.setFloorId(arrangement.getFlId());
        configuration.setRoomId(arrangement.getRmId());
        configuration.setConfigId(arrangement.getConfigId());
        return configuration;
    }
}